services:
  mongodb:
    container_name: mongodb
    image: maheshbabu22neeli/mongodb:1.0.0
    build:
      dockerfile: mongodb.Dockerfile

  catalogue:
    container_name: catalogue
    image: maheshbabu22neeli/catalogue:1.0.0
    build:
      dockerfile: catalogue.Dockerfile
    depends_on:
    - mongodb

  redis:
    container_name: redis
    image: redis:7.0

  user:
    container_name: user
    image: maheshbabu22neeli/user:1.0.0
    build:
      dockerfile: user.Dockerfile
    depends_on:
    - redis

  frontend:
    container_name: frontend
    image: maheshbabu22neeli/frontend:1.0.0
    build:
      dockerfile: frontend.Dockerfile
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user


networks:
  default:
    name: roboshop
    driver: bridge
    external: false # we are creating this network manually, so we set this to false
